### PR TITLE
Release 0.7

### PR DESCRIPTION
**Pull request by westonruter**
- [x] Fix trashing UX (#172)
- [x] Add contributor props.
- [x] Bump version numbers.
- [x] Test build.
- [x] Add changelog to readme.
- [ ] Tag release.

### CODE REVIEW

**Comment by westonruter** [comment]
Post date control is broken in Firefox:

customize__wordpress_develop_ _just_another_customizer-driven_site_

**Comment by westonruter** [comment]
The `details` element isn't fully supported in Firefox yet.

**Comment by sayedwp** [comment]
@westonruter Can we remove `details` tag and show that information in title? like this
`<abbr title="Timezone is America/Ls Angles, currently UTC-7">PDT</abbr>`

**Comment by sayedwp** [comment]
Oh I missed, we are showing more scheduled countdown information there. Then title is not ideal for it, I will write a little bit of JS to replace detail

**Pull request merged**
