### PR TITLE
Use `plugins_url()` directly

### PR DESCRIPTION
**Pull request by danielbachhuber**
This permits filtering of the final URL, which lets me use this plugin as a Git submodule without defining `SCRIPT_DEBUG`

### CODE REVIEW

**Comment by westonruter** [comment]
@danielbachhuber why not use Composer with WordPress Packagist instead? This would then include compiled and minified JS. Eventually if we use Browserify, using a submodule won't be an option.

**Comment by danielbachhuber** [comment]
> why not use Composer with WordPress Packagist instead?

Because I'm managing dependencies with Git submodules. Also, I like the option to be able to easily contribute back while I'm working on the project.

**Comment by westonruter** [comment]
OK, cool. But then eventually you'd need to run `grunt build` anyway if we do any Browserify compilation, right?

**Comment by danielbachhuber** [comment]
> But then eventually you'd need to run grunt build anyway if we do any Browserify compilation, right?

Well, this would break my use of the project completely. My preference would be that you always commit a built copy of the assets to the repo.

**Comment by westonruter** [comment]
@danielbachhuber You may not need to filter your script and style URLs anymore due to https://github.com/xwp/wp-customize-posts/pull/249

**Comment by danielbachhuber** [comment]
Cool, thanks for the heads up 👍

**Pull request merged**
